out_max_length: 500
temperature: 0.1
num_retrievals: 30
metric: 'cosine'
embed_name: 'sentence-transformers/all-MiniLM-L6-v2'
index_name: 'ainews'
dir_path: './output/'
chunk_size: 1000
chunk_overlap: 200
